name = "TemporaryArrays"
uuid = "b2d0ec06-4a30-46b9-b20f-1283d2f7986d"
authors = ["Kyle Sherbert <kyle.sherbert@vt.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
